### PR TITLE
Improve CHANGELOG style against mardownlint

### PR DESCRIPTION
**Pull request by milmazz**
This PR includes the following changes:

* Now the first header is a top level (`#`) header
* Starting bulleted lists at the beginning of the line
* Maximum line length is set to 80 columns
* Headers are now surrounded by blank lines

Also, I added a basic configuration for [mardownlint](https://github.com/DavidAnson/markdownlint), but it's not necessary to be included in the repo, just let me know what do you think?

### CODE REVIEW

**Comment by ericmj** [comment]
Hum, I was always told that markdown lists should be indented, that's what we do in Elixir: https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/project.ex#L42. Also the Elixir changelog: https://raw.githubusercontent.com/elixir-lang/elixir/master/CHANGELOG.md.

I don't think the line length should be enforced because I will probably not enforce strictly in the future and I don't really see the point of it.

The rest looks good 👍

**Comment by milmazz** [comment]
> I don't think the line length should be enforced because I will probably not enforce strictly in the future and I don't really see the point of it.

I know, we can relax that rule if you want, at least in my case I find it useful to have that limit, that way I avoid to scroll so much in the terminal (e.g. `cmd` on Windows) or when I split the layout in my editor.

> I was always told that markdown lists should be indented

According to the original [spec](https://daringfireball.net/projects/markdown/syntax#list):

> **List markers typically start at the left margin**, but may be indented by up to three spaces. List markers must be followed by one or more spaces or a tab.

But again, we can relax that rule.

**Comment by ericmj** [comment]
> I know, we can relax that rule if you want, at least in my case I find it useful to have that limit, that way I avoid to scroll so much in the terminal (e.g. cmd on Windows) or when I split the layout in my editor.

Okay, lets enforce it in this PR and I will try to follow to the best of my ability in the future. But no promises :).

> But again, we can relax that rule.

I think we indented lists originally because some python markdown renderer required it, but it should not matter in this case so let's dedent.

If you remove the markdownlint file we are good to merge 👍

**Comment by milmazz** [comment]
> Okay, lets enforce it in this PR and I will try to follow to the best of my ability in the future. But no promises :).

Thanks!

**Comment by wojtekmach** [comment]
Thank you! 😍

**Pull request merged**
