### PR TITLE
refactor create docs function

### LINKED ISSUE #591: Add checks before publishing docs
* [ ] The uncompressed size of the docs tarball should be <64mb, this means we probably have to build the tarball and compress it as two steps.
* [x] Root directory names can not be valid semver versions, otherwise we can have conflicts between unversioned docs https://hexdocs.pm/elixir and versioned docs https://hexdocs.pm/elixir/1.6.6.

These checks are performed by hexpm right now, but the upload process will move to a separate service making the process sync. This makes it harder to give users feedback on these issues which means we should try and detect them in the client.

### PR DESCRIPTION
**Pull request by WanjikuMac**
Fixes #591 

# Changes proposed
 - Refactor to create docs function

### CODE REVIEW

**Comment by zacck** [comment]
@theodowling  is the current fail due to the changes you added?  perhaps we can squash all this into one commit?

**Comment by theodowling** [comment]
Hey @zacck - Unfortunately I don't think the issues are linked to my PR, and squashing into one commit will also not really have the desired affect.

I've had a quick look and I suggest the following - even though this is untested:

```
  defp build_tarball(directory) do
    files = files(directory)

    raise_if_file_matches_semver(files)

    {:ok, {data, _checksum}} = :mix_hex_tarball.create_docs(files)
    
    data
  end
```

And then update https://github.com/hexpm/hex/blob/f8a86fba8f2080f9f278494d8cf68e8f8e8561be/lib/mix/tasks/hex.publish.ex#L174 to be just ```tarball = build_tarball(directory)```

**Comment by zacck** [comment]
@WanjikuMac you would need to rebase this PR on master and then we can follow the suggestions to get this going, good effort into your OSS foray! @ericmj  @theodowling thank you guys so much for the guidance 🙏

**Comment by WanjikuMac** [comment]
@theodowling @ericmj @zacck  what is causing the checks to fail

**Comment by zacck** [comment]
@WanjikuMac  this is your failing test test/mix/tasks/hex.publish_test.exs:113

**Comment by zacck** [comment]
@WanjikuMac ^^^

**Comment by WanjikuMac** [comment]
@zacck @ericmj fixing the bug so that the process can receive the message. Apologies for the delay

**Comment by WanjikuMac** [comment]
@ericmj the process mailbox receives a message and all the tests are passing locally, could you please assist.

**Comment by ericmj** [comment]
Thank you!

**Comment by supersimple** [comment]
Thanks! 🦄

**Pull request merged**
