### PR TITLE
Checks for uncompressed tar size while creating

### PR DESCRIPTION
**Pull request by supersimple**
Fixes part 1 of https://github.com/hexpm/hex/issues/591

I will be absolutely amazed if I got this entirely correct on the first try, but if not, hopefully this can be a jumping-off point for improvements.

### CODE REVIEW

**Comment by wojtekmach** [comment]
1. The ticket is about docs tarball size, not package tarball size. We already check compressed package tarball size, I dont think we need additional check.
2. All Erlang code is vendored from https://github.com/hexpm/hex_erl so any changes should be done upstream and they we would manually vendor them.

**Comment by ericmj** [comment]
The check should be for docs like @wojtekmach said, but I think this could be a nice check to have for packages also. WDYT @wojtekmach?

**Comment by wojtekmach** [comment]
@ericmj ok to keep it 👍

**Comment by ericmj** [comment]
@supersimple Thanks for the PR. Can you move the check to the hex_erl library as @wojtekmach suggested and add a check for the docs tarball size as well?

**Comment by wojtekmach** [comment]
Fixed in hex_erl.

**Pull request closed without merging**
