### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by khusnetdinov**
Relate to https://github.com/hexpm/hex/issues/299

### CODE REVIEW

**Comment by khusnetdinov** [comment]
Is this actual? Need fix or close?

**Comment by ericmj** [comment]
Maybe we should combine the config and environment variables because most have parallels in the other but I'm not sure how we should do it yet.

**Comment by khusnetdinov** [comment]
Well I did it this way. Put all in one place, in this way we can see all for configuring. look here https://github.com/khusnetdinov/hex/blob/e5fb35de62faf00d1d0ee87025b5e01ab79c4b5e/lib/mix/tasks/hex/config.ex

**Comment by khusnetdinov** [comment]
Update

**Comment by ericmj** [comment]
I don't want to only move the text to the same file. The problem is that we split environment variables and config keys when many of them do the same thing. They are also inconsistent today, for example `http_concurrency` mentions `HEX_HTTP_CONCURRENCY`, but `http_proxy` does not mention `HTTP_PROXY`.

We need to structure it in a way that it's easy to find all related options.

**Comment by khusnetdinov** [comment]
Ok, I'll try to review them all and refactor, thank for clear problem.

**Comment by wojtekmach** [comment]
> The problem is that we split environment variables and config keys when many of them do the same thing. They are also inconsistent today

agreed. I think we could make it so that each config key `foo` has a corresponding `HEX_FOO` environment variable that can overwrite it. So, instead of `HEX_API` for `api_url` we would have `HEX_API_URL` [1] [2] WDYT? 

This way it could be documented in just one place using the same wording:

```markdown
(based on https://github.com/hexpm/hex/blob/v0.14.0/lib/mix/tasks/hex/config.ex#L11)

 ## Config keys

    * `username` - Hex username, can be overridden by setting
      the environment variable `HEX_USERNAME`
    ...
    * `api_url` - Hex API URL, can be overridden by setting
      the environment variable `HEX_API` (Default: `https://hex.pm/api`)
    ...
```

and then in other places, if needed, we could say something like:

> run `mix help hex.config` to see all available configuration options

@ericmj WDYT?

[1] this would be a breaking change so we should release it in v0.15. Also, probably not a huge deal anyway as people should rarely depend on env vars
[2] We didn't provide `HEX_USERNAME`/`HEX_KEY` yet but I think it won't hurt and we could use it for debugging auth related stuff.

**Comment by ericmj** [comment]
> WDYT?

Sounds great. :+1:

> this would be a breaking change so we should release it in v0.15. Also, probably not a huge deal anyway as people should rarely depend on env vars

We can support both for a while with a deprecation warning also.

**Comment by wojtekmach** [comment]
Deprecation warning sounds good :+1:

**Comment by wojtekmach** [comment]
@khusnetdinov Ping? I think we now have a pretty good idea what needs to happen here, let us know if you're still interested/able to work on this

**Comment by khusnetdinov** [comment]
@wojtekmach, Sorry for my late reply. Unfortunately I don't have time. It had better to ask somebody other in this time. Sorry :cry:

**Comment by wojtekmach** [comment]
no worries, thanks for the heads up and for sparking a discussion on this - I think we reached a good conclusion that will definitely be an improvement to the cli.

**Comment by ericmj** [comment]
Thanks for your PR @khusnetdinov.

**Pull request closed without merging**
