### PR TITLE
Suggest `runtime: false` for ex_doc dependency

### PR DESCRIPTION
**Pull request by wojtekmach**

### CODE REVIEW

**Comment by ericmj** [comment]
What does that do when we have `only: :dev`?

**Comment by wojtekmach** [comment]
without `runtime: false` it's gonna be added to loaded applications list. Which to be fair, it's not a big deal (especially that ExDoc does not even have application callback module). I think tools like ex_doc, dialyxir etc should have `runtime: false` (unless someone actually uses their APIs at runtime) and that's what their recommend in their respective READMEs.

**Comment by ericmj** [comment]
Please do the same change here: https://github.com/hexpm/hex/blob/master/lib/mix/tasks/hex.publish.ex#L204

**Comment by wojtekmach** [comment]
@ericmj that's where I made the change :joy:

**Comment by ericmj** [comment]
Eeeh...

Let's try this then: https://github.com/hexpm/hexpm/blob/master/lib/hexpm_web/templates/docs/publish.html.md#example-mixexs-file

**Comment by wojtekmach** [comment]
Yup!

**Pull request merged**
