### PR TITLE
Print a link to the CoC when publishing packages

### PR DESCRIPTION
**Pull request by whatyouhide**
Took a stab at #105, just to get a feeling of Hex's codebase so that I can try to be more helpful in the future :). Let me know what you think, thanks!

### CODE REVIEW

**Comment by ericmj** [comment]
Looks great but we shouldn't include newlines.

**Comment by whatyouhide** [comment]
@ericmj makes sense, `push --force`d over the old commit :)

**Comment by jcspencer** [comment]
Looks good to me :+1:

**Comment by ericmj** [comment]
Thank you!

**Pull request merged**
