### PR TITLE
Make repository more prominent in hex.publish

### PR DESCRIPTION
**Pull request by wojtekmach**
Ref #424

Before:

screen shot 2017-10-29 at 21 25 30

After:

screen shot 2017-10-29 at 21 24 04
screen shot 2017-10-29 at 21 24 26

### CODE REVIEW

**Comment by josevalim** [comment]
It may be better to use bold and ** around the text. ANSI colors do not
work one windows and may be less readable depending on the background
color, so we need to be careful when relying on them for emphasis.
-- 


*José Valimwww.plataformatec.com.br
<http://www.plataformatec.com.br/>Founder and Director of R&D*

**Comment by wojtekmach** [comment]
If there's a way to detect whether a shell supports escape codes then perhaps we could still use colours but fallback to text emphasis? I do agree that using these particular colours might be problematic for users with light background, will do some research.

What I wanted to achieve with using _different_ colours is to train users to treat cyan as public=safe, yellow as private=warning. FWIW this is only really an issue on the first publish when the user forgets to set the proper organisation in mix.exs; afterwards it's hard to make a mistake. So maybe there are some other solutions to achieve the same goal?

**Comment by josevalim** [comment]
`IO.ANSI.enabled?`

**Comment by wojtekmach** [comment]
Ok, I think I was framing the problem wrong. If the problem is that users didn't pay attention where it's being published then it shouldn't matter that much if we differentiate between public/private - it should be enough to have some more emphasis in the first place. And then down the road differentiation is less important because presumably the user configured `mix.exs` correctly.

How about:

1. screen shot 2017-10-30 at 09 22 56

or 

2: screen shot 2017-10-30 at 09 28 59

**Comment by josevalim** [comment]
Here is an idea, why don't we also minimize the amount of information shown?

```
Building package shipit 0.2.3 (use --verbose to see package contents)
All packages must follow Hex Code of Conduct: https://hex.pm/coc
...warnings...

Publishing package to **public** repository hexpm.
Proceed? [Yn]
```

Regarding the Hex Code of Conduct, you could also store a configuration on the user machine with the code of conduct version and show it only the first time the user publishes a package:

```
Before publishing, please read Hex Code of Conduct: https://hex.pm/coc
Agreed? [Yn]
```

Even if you don't agree with those for now, I would at least change the first Publishing mention to Building, otherwise you get Publishing appearing multiple times. :)

**Comment by josevalim** [comment]
@wojtekmach you can also use IO.ANSI.enabled? to alternative between `**public**` and `public` in bold.

**Comment by wojtekmach** [comment]
> I would at least change the first Publishing mention to Building

sounds good to me, applied.

Regarding two other proposals (for CoC and verbose mode) I like them. WDYT @ericmj? Would be a separate PRs obviously.

**Comment by ericmj** [comment]
👍 for changing publishing to building.

I would like to avoid storing more local state because it's fragile and hard to test so I am 👎 on not always showing CoC link.

Not sure about verbose mode because people easily make mistakes, see recent ex_doc issue, and this is one of the only ways for us to show what we are actually packaging. Hiding this output behind an option is effectively removing the output.

**Comment by josevalim** [comment]
> see recent ex_doc issue

Exactly. I don't read those and I don't think anybody does after the package is published for the first time.

**Comment by ericmj** [comment]
> Exactly. I don't read those and I don't think anybody does after the package is published for the first time.

I don't think the solution is to completely remove the output. The only other way we have to verify the package today is the smoke test which is opt-in and does not find all issues that the package contents output can show. Until we have better solution we should keep showing the output.

**Pull request merged**
