### PR TITLE
Remove retire warning

### PR DESCRIPTION
**Pull request by ericmj**

### CODE REVIEW

**Comment by supersimple** [comment]
what makes this not useful anymore?

**Comment by ericmj** [comment]
It is useful but sometimes incorrect. For example if you are retiring because of deprecation or renaming you may not want to publish a new version.

Maybe we should check the retirement reason before printing the message.

**Comment by ericmj** [comment]
Another note is that with the new resolver we can prioritize the version we pick and deprioritize retired versions so they are only picked if there is no stable version matching the requirement.

**Comment by supersimple** [comment]
> Maybe we should check the retirement reason before printing the message.
Maybe, but they are somewhat vague. Probably not worth it IMO.

> Meaning that retiring WILL affect version resolution. 
This seems dangerous. Having resolution change unexpectedly to the end-user seems not ideal. Perhaps there could be a flag to allow/disallow this behaviour.

**Review by supersimple — APPROVED** [review]

**Pull request merged**
