### PR TITLE
[WIP #135] Providing task for downloading docs 

### PR DESCRIPTION
**Pull request by rodrigopinto**
Hi @ericmj @josevalim.

I'm working on issue #135 and I'm going to do it step by step. So, it's a WIP but I would really appreciate any review already to help me if I'm on correct path.

- [x] Move current mix `hex.docs` to `mix hex.publish docs`
- [x] Current `mix hex.publish` becomes `mix hex.publish package` (although today's syntax still works)
- [ ] Add `mix hex.docs open | fetch PACKAGE [VERSION]` - if no version is present, uses the latest

### CODE REVIEW

**Comment by rodrigopinto** [comment]
The CI breaks testing against elixir master branch, that now just support Erlang VM 18.0. Let's move support just 18.0 too!?

**Comment by ericmj** [comment]
We need to test against older elixir versions because this project is used to test the hex client which should work with all stable elixir versions. I updated travis.yml to build correctly so your PR should also pass.

**Comment by ericmj** [comment]
I like all your changes so far. If you can avoid updating the mix.lock please do.

**Comment by rodrigopinto** [comment]
@ericmj Ok. About the lock file, I'll try to not change `mix.lock` but when I was setting up the dev env, I run `mix install` and `mix test` and get:

```shell
➜  hex git:(issue-135) ✗ mix test
Unchecked dependencies for environment test:
* comeonin (Hex package)
  the dependency is not locked
* hex_web (git://github.com/hexpm/hex_web.git)
  lock outdated: the lock is outdated compared to the options in your mixfile
** (Mix) Can't continue due to errors on dependencies
```
So, I run `mix deps.get` to install the dependencies and it update the `mix.lock`. Am I doing anything wrong?

**Comment by ericmj** [comment]
Okay, that's perfectly fine then. It was my mistake forgetting to update
the lock.

On Tuesday, 6 October 2015, Rodrigo Pinto <notifications@github.com> wrote:

> @ericmj <https://github.com/ericmj> Ok. About the lock file, I'll try to
> not change mix.lock but when I was setting up the dev env, I run mix
> install and mix test and get:
>
> ➜  hex git:(issue-135) ✗ mix test
> Unchecked dependencies for environment test:* comeonin (Hex package)
>   the dependency is not locked* hex_web (git://github.com/hexpm/hex_web.git)
>   lock outdated: the lock is outdated compared to the options in your mixfile** (Mix) Can't continue due to errors on dependencies
>
> So, I run mix deps.get to install the dependencies and it update the
> mix.lock. Am I doing anything wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hexpm/hex/pull/142#issuecomment-145867955>.
>


-- 
Eric Meadows-Jönsson

**Comment by ericmj** [comment]
@rodrigopinto Let me know if something is blocking you or you need any help to finish the PR.

**Comment by rodrigopinto** [comment]
Hey @ericmj thanks for your support. To be honest I've being busy and I am not having enough spare time to take a look to finish it. If it is blocking you, feel free to complete the missing task. I'll try to finish as soon as I get a time. :smile:

**Comment by ericmj** [comment]
Ping? If you don't have time to finish this let us know so someone else can continue it. Thanks for your work.

**Pull request closed without merging**
