### PR TITLE
Fix bug when umbrella child has dependency with :only

### PR DESCRIPTION
**Pull request by josevalim**
Because dependencies with :only are filtered later in Elixir
v1.2, flatten deps would still find such dependencies in the
dep.deps parameter, causing the converger to fail later on.

This commit fixes the issue by only keeping dependencies that
were seen in the original list of deps.

### CODE REVIEW

**Comment by ericmj** [comment]
Does this fix it only for 1.2.1 or 1.2.0 also?

**Comment by josevalim** [comment]
Fix for all, there is nothing to do on the elixir side.

**Comment by Gazler** [comment]
I am getting a different error now on https://github.com/Gazler/hex_resolve_issue

```
remote: Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/phoenix-1.1.1.tar)
remote: Using locally cached package
remote: * Getting phoenix_html (Hex package)
remote: Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/phoenix_html-2.3.0.tar)
remote: Using locally cached package
remote: * Getting phoenix_live_reload (Hex package)
remote: Checking package (https://s3.amazonaws.com/s3.hex.pm/tarballs/phoenix_live_reload-1.0.1.tar)
remote: ** (exit) exited in: GenServer.call(:hex_fetcher, {:await, {:phoenix_live_reload, "1.0.1"}}, 60000)
remote:     ** (EXIT) time out
remote:     (elixir) lib/gen_server.ex:564: GenServer.call/3
remote:     (hex) lib/hex/scm.ex:82: Hex.SCM.checkout/1
remote:     (mix) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
remote:     (mix) lib/mix/dep/converger.ex:164: Mix.Dep.Converger.all/8
remote:     (mix) lib/mix/dep/converger.ex:173: Mix.Dep.Converger.all/8
remote:     (mix) lib/mix/dep/converger.ex:47: Mix.Dep.Converger.converge/4
remote:     (mix) lib/mix/dep/fetcher.ex:16: Mix.Dep.Fetcher.all/3
remote:     (mix) lib/mix/tasks/deps.get.ex:22: Mix.Tasks.Deps.Get.run/1
```

**Comment by josevalim** [comment]
Should be fixed in Elixir master.

**Pull request merged**
