### PR TITLE
Windows tests

### PR DESCRIPTION
**Pull request by TroyLaurin**
So first a fix to the test that was broken by the hex.docs open fix.
Second a fix to the resolver tests where Elixir thinks ANSI is unsupported.

There's still 9 test failures, all in the integration suite.  See https://github.com/hexpm/hex/issues/525 for details.

### CODE REVIEW

**Comment by ericmj** [comment]
Is there no way to force windows to use ANSI sequences also?

/cc @josevalim

**Comment by josevalim** [comment]
You can use Application.put_env(:elixir, :ansi_enabled, true | false) in the test helper. I would set it to false though, it simplifies tests.

**Comment by ericmj** [comment]
The problem is that in some tests, for example `hex.outdated` we want to test the colors. But I guess it's better to opt-in with `:ansi_enabled` for those tests instead.

**Comment by ericmj** [comment]
@TroyLaurin Did you get a chance to try the approach @josevalim suggested? Would love to improve Windows support in Hex.

**Comment by TroyLaurin** [comment]
Hey, I'd gotten a bit busy at work and let this slip.  I've pushed what I think @josevalim is suggesting, and it passes all the tests but 5 now.

Actually, I see now that the in_tmp is a custom function and not part of the ExUnit case class, so I've pushed a fix for that too.  The remaining failures seem minor:

```
$ mix test
Excluding tags: [:skip]

..............................................................................................

  1) test create with files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:41
     Assertion with != failed, both sides are exactly equal
     code: assert File.stat!("unzip/empty_dir").mtime() != mtime_empty_dir
     left: {{2018, 3, 20}, {6, 6, 54}}
     stacktrace:
       test/mix/tasks/hex.build_test.exs:69: anonymous fn/0 in Mix.Tasks.Hex.BuildTest."test create with files"/1
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:44: (test)

.......

  2) test create with excluded files (Mix.Tasks.Hex.BuildTest)
     test/mix/tasks/hex.build_test.exs:84
     Assertion with == failed
     code:  assert File.stat!("unzip/myfile.txt").mode() == 33188
     left:  33206
     right: 33188
     stacktrace:
       (elixir) lib/file.ex:1419: File.cd!/2
       test/mix/tasks/hex.build_test.exs:87: (test)

......................................................................

Finished in 9.7 seconds
2 properties, 178 tests, 2 failures, 7 skipped

Randomized with seed 605000
```

**Comment by TroyLaurin** [comment]
The old regex tests should still be visible at f56bf55

**Comment by TroyLaurin** [comment]
Rebased to master

**Pull request merged**
