### PR TITLE
feat(mix hex.outdated): add the hex.pm package url to the outdated task

### PR DESCRIPTION
**Pull request by tomciopp**
Let me know what you think

### CODE REVIEW

**Comment by ericmj** [comment]
This is tricker than I initially thought because we can't assume hex.pm as the website url. 

Also see: https://github.com/hexpm/hex/pull/400.

**Comment by tomciopp** [comment]
@ericmj Can you elaborate a little more? Based on my quick reading of the code there is a filter function in this module that I thought would allow us to make that assumption. I've reprinted it below.

    deps = Mix.Dep.loaded([]) |> Enum.filter(& &1.scm == Hex.SCM)

If there are edge cases or things I am not aware of can you let me know?

**Comment by ericmj** [comment]
> If there are edge cases or things I am not aware of can you let me know?

The problem is that there are other APIs than hex.pm. You can change it in the config and with environment variables, when using another API packages wont end up on hex.pm.

**Comment by tomciopp** [comment]
Ah, ok let me do a little bit more research and I will update this PR

**Comment by ericmj** [comment]
I don't think we can change this without reworking how hex.outdated works. We are planning to add something similar to the hex.pm website, if we also make it part of the API we could use that in the future.

**Pull request closed without merging**
