### PR TITLE
feat: allow to fetch packages from self-hosted Hex instances

### PR DESCRIPTION
**Pull request by milmazz**
Fixes: #789

### CODE REVIEW

**Comment by wojtekmach** [comment]
Thank you @milmazz, besides the changes themselves which look good to me, this PR made my realise that I introduced a bug and should improve docs at `mix local.install --repo` (https://github.com/elixir-lang/elixir/pull/10121#issuecomment-648214021) so I'm grateful for that too :)

**Comment by ericmj** [comment]
Thank you!

**Comment by milmazz** [comment]
@wojtekmach @ericmj Always happy to help o/

**Comment by wojtekmach** [comment]
Worth mentioning that all of the below are equivalent:

```
mix hex.package fetch myapp 0.1.0 --organization hex
mix hex.package fetch myapp 0.1.0 --repo hexpm --organization hex
mix hex.package fetch myapp 0.1.0 --repo hexpm:hex
```

perhaps we shouldn't allow explicitly passing `--repo hexpm:hex`, i.e. if someone wants to access org they should use `--organization`? At the same time the `<repo>:<org>` is showed e.g. here:

```
~% mix hex.repo list
Name       URL                                 Public key                                          Auth key
hexpm      https://repo.hex.pm (...)
hexpm:hex  https://repo.hex.pm/repos/hex (...)
```

so maybe it would be counterproductive to not allow it as `--repo` after all? I think keeping things as we have them right now is totally fine, just wanted to explicitly mention this before we ship it.

**Comment by ericmj** [comment]
@wojtekmach I think how it works currently is fine.

**Pull request merged**
