### PR TITLE
Add KeyManager and ContentEncryptor to handle encryption of api key

### PR DESCRIPTION
**Pull request by potatosalad**
I put this together after some questions by @ericmj [yesterday on IRC](https://botbot.me/freenode/elixir-lang/msg/69148630/) about #244.

Hopefully this is helpful and not a headache.

### Summary of changes

1. `Hex.Crypto.encrypt/3` and `Hex.Crypto.decrypt/3` are now opaque functions that take a plain/cipher text, password, and tag.  A single binary is returned containing all additional necessary data to authenticate, derive password challenges, and decrypt.
2. Instead of storing both `:key_cipher` and `:key_salt`, a single `:encrypted_key` binary is stored for the encrypted api key.
3. Added `Hex.Crypto.KeyManager` and `Hex.Crypto.ContentEncryptor` to allow for separation between Key Management and Content Encryption algorithms.
4. Altered some of the algorithms to follow guidelines in published standards:
   1. `AES-CBC` replaced with `AES_CBC_HMAC_SHA2` for authenticated content encryption [RFC 7518 Section 5.2.6](https://tools.ietf.org/html/rfc7518#section-5.2.6).
   2. `PBKDF2` replaced with `PBES2_HMAC_SHA2_AES_KW` for key management encryption [RFC 7518 Section 4.8](https://tools.ietf.org/html/rfc7518#section-4.8).

Additionally, there is disabled-by-default support for `AES-GCM` lurking in the shadows.  Once support for OTP-17 has been removed, I'd recommend switching to `AES-GCM` for all new encrypted keys.  Older `AES-CBC` encrypted keys can still be decrypted once other new modes are active.

### How does it work?

1. A randomly generated `key`, `iv`, and `salt` are used for each encryption operation.
2. A `protected` header is built which contains information about the Key Manager and Content Encryptor used.
3. The `tag` is prepended onto `protected` and used as the `aad` value for the content encryption of the `plain_text` into `cipher_text` and `cipher_tag`.
4. The `key` is encrypted using AES Key Wrap with a key-encryption key derived from PBKDF2 using the `password`, `salt`, and `iterations` into `encrypted_key`.
5. The `protected`, `encrypted_key`, `iv`, `cipher_text`, and `cipher_tag` are encoded as described below.

The encoded encryption is a variant of [JWE Compact Serialization](https://tools.ietf.org/html/rfc7516#section-3.1), which is essentially:

```text
BASE64URL(protected) || '.' ||
BASE64URL(encrypted_key) || '.' ||
BASE64URL(iv) || '.' ||
BASE64URL(cipher_text) || '.' ||
BASE64URL(cipher_tag)
```

The `protected` header contains information related to which Key Management and Content Encryption algorithm were used (by default, `PBES2-HS512+A256KW` and `A256CBC-HS512`, respectively).

For `PBES2_HMAC_SHA2_AES_KW`, the `protected` header also contains the `salt` and `iterations` values that were used at the time of encryption.

The `tag` passed to either `encrypt/3` or `decrypt/3` gets prepended to `protected` and becomes the value used for the Additional Authenticted Data (or `aad`).

Beyond that, the functions are designed to be opaque.

##### Example encryption/decryption

```elixir
cipher_text = Hex.Crypto.encrypt("test", "password", "apikey")
# => "VlVWS1JsVjZTWFJUUmsweFRWUkpjbEZVU1RGT2EzUllMbFJFVG1waWJrMTRURmRTTmxWSGJHOWhSVTVMVkRKT2JtVldhekpSVXpWdVVWVkYuVVZSSk1VNXJUa05SZVRGSlZYcFZlRTFuTGc.9sQ46kICihrgzYfnYHziKjJHjqH8vAUlDcXLWfMD9ayzPZafTbqmpYi3DB7Q1A69RnFza1o0LinlKJplCSoWttisoaaKHxG_.2TahiPUFpxVYBcrcLhQKwQ.tj4Wq4qUb9sByt8e7zZCNg.n1Nq8z5vIpabr7JfF3WK597qWOpK7F0ZzZLeQBMdfGw"
{:ok, plain_text} = Hex.Crypto.decrypt(cipher_text, "password", "apikey")
# => {:ok, "test"}
```

##### Example encryption without any magic

```elixir
alias Hex.Crypto.AES_CBC_HMAC_SHA2
alias Hex.Crypto.PBES2_HMAC_SHA2_AES_KW

# Parameters passed to encrypt/3
plain_text = "test"
password   = "password"
tag        = "apikey"

# Numeric Variables
key_length         = 64
iv_length          = 16
derived_key_length = 32
salt_length        = 16
iterations         = Hex.State.fetch!(:pbkdf2_iters) # => 32768

# Randomly Generated Variables
key  = :crypto.strong_rand_bytes(key_length)
iv   = :crypto.strong_rand_bytes(iv_length)
salt = :crypto.strong_rand_bytes(salt_length)

# Build the Protected Header
key_manager_protected = ([
  "PBES2-HS512+A256KW" |> Base.url_encode64(padding: false),
  ".",
  ([
    salt |> Base.url_encode64(padding: false),
    ".",
    iterations |> :binary.encode_unsigned(:big) |> Base.url_encode64(padding: false)
  ]
  |> IO.iodata_to_binary()
  |> Base.url_encode64(padding: false))
]
|> IO.iodata_to_binary())

content_encryptor_protected = ([
  "A256CBC-HS512" |> Base.url_encode64(padding: false),
  "."
]
|> IO.iodata_to_binary())

protected = ([
  key_manager_protected |> Base.url_encode64(padding: false),
  ".",
  content_encryptor_protected |> Base.url_encode64(padding: false)
]
|> IO.iodata_to_binary())

# Additional Authenticated Data is tag prepended onto protected
aad = tag <> protected

# Content Encryption
{cipher_text, cipher_tag} = AES_CBC_HMAC_SHA2.content_encrypt({aad, plain_text}, key, iv)

# Key Encryption
encrypted_key = PBES2_HMAC_SHA2_AES_KW.key_encrypt(key, password, salt, iterations, derived_key_length)

# Encode Encrypted Token
encrypted_token = ([
  protected |> Base.url_encode64(padding: false),
  ".",
  encrypted_key |> Base.url_encode64(padding: false),
  ".",
  iv |> Base.url_encode64(padding: false),
  ".",
  cipher_text |> Base.url_encode64(padding: false),
  ".",
  cipher_tag |> Base.url_encode64(padding: false)
]
|> IO.iodata_to_binary())
# => "VlVWS1JsVjZTWFJUUmsweFRWUkpjbEZVU1RGT2EzUllMbFI2VGxoWmEzUlFaVVZPTUZwWFdrbGtia0kyVVcxT1FtSldTVEZSVXpWdVVWVkYuVVZSSk1VNXJUa05SZVRGSlZYcFZlRTFuTGc.AOzy2WFU6_uXRRmbq-jZKNj5trKTYxMQPRssYZ6OVB995ohgeogC5fueefsHtL3yZW-TMrl_IHWtbnwPeumAvS_5tSMoPnAh.LkfGmu9qiIdQ5p2n43Esvg.ZoIJst0LluRwm9VHyesq2w.ZvwBMiFmj_oxYRE0cHkqiNoZ7epeTFHkv5Ln6z5IAkQ"
```

##### Example decryption without any magic

```elixir
alias Hex.Crypto.AES_CBC_HMAC_SHA2
alias Hex.Crypto.PBES2_HMAC_SHA2_AES_KW

# Parameters passed to decrypt/3
cipher_text = "VlVWS1JsVjZTWFJUUmsweFRWUkpjbEZVU1RGT2EzUllMbFI2VGxoWmEzUlFaVVZPTUZwWFdrbGtia0kyVVcxT1FtSldTVEZSVXpWdVVWVkYuVVZSSk1VNXJUa05SZVRGSlZYcFZlRTFuTGc.AOzy2WFU6_uXRRmbq-jZKNj5trKTYxMQPRssYZ6OVB995ohgeogC5fueefsHtL3yZW-TMrl_IHWtbnwPeumAvS_5tSMoPnAh.LkfGmu9qiIdQ5p2n43Esvg.ZoIJst0LluRwm9VHyesq2w.ZvwBMiFmj_oxYRE0cHkqiNoZ7epeTFHkv5Ln6z5IAkQ"
password    = "password"
tag         = "apikey"

# This assumes everything is well-formed and does not do proper error checking.
[
  protected,
  encrypted_key,
  iv,
  cipher_text,
  cipher_tag
] = (cipher_text
|> String.split(".")
|> Enum.map(&Base.url_decode64!(&1, padding: false)))

[
  key_manager_protected,
  content_encryptor_protected
] = (protected
|> String.split(".")
|> Enum.map(&Base.url_decode64!(&1, padding: false)))

# Decode the Key Manager and its parameters
[
  "PBES2-HS512+A256KW",
  key_manager_params
] = (key_manager_protected
|> String.split(".")
|> Enum.map(&Base.url_decode64!(&1, padding: false)))

derived_key_length = 32 # based on PBES2-HS512+A256KW matched above

[
  salt,
  iterations
] = (key_manager_params
|> String.split(".")
|> Enum.map(&Base.url_decode64!(&1, padding: false)))

iterations = :binary.decode_unsigned(iterations, :big)

# Decode the Content Encryptor and its parameters
[
  "A256CBC-HS512",
  ""
] = (content_encryptor_protected
|> String.split(".")
|> Enum.map(&Base.url_decode64!(&1, padding: false)))

# Additional Authenticated Data is tag prepended onto protected
aad = tag <> protected

# Key Decryption
{:ok, key} = PBES2_HMAC_SHA2_AES_KW.key_decrypt(encrypted_key, password, salt, iterations, derived_key_length)

# Content Decryption
{:ok, plain_text} = AES_CBC_HMAC_SHA2.content_decrypt({aad, cipher_text, cipher_tag}, key, iv)
# => {:ok, "test"}
```

### Future brainstorming

By separating the content encryption and key management operations, these design changes should allow for future algorithms to easily be added while maintaining backwards compatibility with older algorithms.

This would also allow, for example, support for encryption based on SSH keys (RSA, EC, and Ed25519) rather than a password alone (although the keys themselves can be encrypted externally with a password).

### CODE REVIEW

**Comment by ericmj** [comment]
Hi @potatosalad. Sorry for the slow response while I have been trying to digest this (no pun intended).

This looks amazing but I am worried that it is too complex compared to the somewhat small feature we are doing. For example, this supports forward compatibility which is not required for us since we control the entire chain between encryption, decryption and storage. I am afraid that I will not be able to maintain this if you are not around. 

Can you list the individual improvements for each part compared to the original encryption scheme so that we can look at them individual and see if what's needed?

**Comment by potatosalad** [comment]
First, I agree this is probably too complex in the context of its usage as a relatively small feature in its current form.  I take no offense if you feel it best to reject this pull request at any time.

In my opinion, the value of having this in Hex is with future features where local cryptography might be necessary.

> Can you list the individual improvements for each part compared to the original encryption scheme so that we can look at them individual and see if what's needed?

Sure, here's a comparison table.

| Operation                        | Old        | New             | Future     |
| -------------------------------- | ---------- | --------------- | ---------- |
| Content-Encryption               | AES256-CBC | AES256-CBC      | AES256-GCM |
| Message-Authentication           |            | HMAC-SHA256     | AES256-GCM |
| Key-Encryption                   |            | AES256 Key Wrap | AES256-GCM |

The "Future" column there is to show how much of the complexity may be reduced over time.  Some of the current complexity is due to using soon-to-be-legacy algorithms in order to support OTP 17.  Even more-future-than-that algorithms like AES-GCM-SIV may further reduce complexity.

In other words, future maintenance should (hopefully) involve removing legacy code as we move towards having a few native `:crypto` calls that do everything required.

Here's another table describing the keys/vectors/salts generated for the above operations.

| Key Generation                   | Old               | New               |
| -------------------------------- | ----------------- | ----------------- |
| Content-Encryption Key (CEK)     | PBES2 HMAC-SHA256 | Random            |
| Message-Authentication Key (MAK) |                   | Random            |
| Initialization Vector (IV)       | PBES2 HMAC-SHA256 | Random            |
| Key-Encryption Key (KEK)         |                   | PBES2 HMAC-SHA256 |
| PBKDF2 Salt                      | Random            | Random            |

Most of my reasoning behind these changes are based on [RFC 5652: Cryptographic Message Syntax](https://tools.ietf.org/html/rfc5652) which was published in 2009.

> Implementations must randomly generate content-encryption keys, message-authentication keys, initialization vectors (IVs), and padding.  Also, the generation of public/private key pairs relies on random numbers.  The use of inadequate pseudo-random number generators (PRNGs) to generate cryptographic keys can result in little or no security.

The original implementation ([`lib/hex/crypto.ex` line 5](https://github.com/hexpm/hex/blob/77231f7545933b284e46a386b5a4e24dda10e399/lib/hex/crypto.ex#L5)) uses PBKDF2 as a PRNG to directly generate the content-encryption key (CEK) and initialization vectors (IV).  A better solution is to use `:crypto.strong_rand_bytes/1` to generate the CEK and IV.

> Implementations must protect the key management private key and the message-authentication key.
> 
> The content-encryption key is encrypted for each recipient.
> 
> The message-authentication key is encrypted for each recipient.
> 
> [For] passwords: the content-encryption key is encrypted in a key-encryption key that is derived from a password or other shared secret value.

The original implementation neither encrypts the content-encryption key (CEK) nor generates a message-authentication key (MAK).  A better solution is to use PBKDF2 to derive the key-encryption key (KEK) which can be used to encrypt the CEK and MAK with AES Key Wrap.

> Implementers should be aware that cryptographic algorithms become weaker with time.  As new cryptoanalysis techniques are developed and computing performance improves, the work factor to break a particular cryptographic algorithm will be reduced.  Therefore, cryptographic algorithm implementations should be modular, allowing new algorithms to be readily inserted.  That is, implementers should be prepared for the set of algorithms that must be supported to change over time.

This paragraph sums up my opinions about the reasons why I included forward compatibility.  Upon switching to AES-GCM (or another future algorithm), Hex should decrypt the AES-CBC content and re-encrypt using the new algorithm.  The user won't be aware that anything has changed.

Authenticated Encryption with Associated Data (AEAD) provides a way to check its integrity and authenticity of encrypted content as mentioned in [RFC 5116: An Interface and Algorithms for Authenticated Encryption](https://tools.ietf.org/html/rfc5116) which was published in 2008.

> It benefits the application designer by allowing them to focus on important issues such as security services, canonicalization, and data marshaling, and relieving them of the need to design crypto mechanisms that meet their security goals.

The original implementation prepends the plain text with `"HEXAPIKEY"` ([`lib/hex/crypto.ex` line 6](https://github.com/hexpm/hex/blob/77231f7545933b284e46a386b5a4e24dda10e399/lib/hex/crypto.ex#L6)) and then uses that prefix as a form of data integrity checking upon decryption ([`lib/hex/crypto.ex` lines 48-57](https://github.com/hexpm/hex/blob/77231f7545933b284e46a386b5a4e24dda10e399/lib/hex/crypto.ex#L48-L57)).  A better solution is to use HMAC-SHA256 in combination with AES256-CBC to provide data integrity and authenticity of the encrypted content as described in [Authenticated Encryption with AES-CBC and HMAC-SHA](https://tools.ietf.org/html/draft-mcgrew-aead-aes-cbc-hmac-sha2-05) and [RFC 7518: JSON Web Algorithms (JWA)](https://tools.ietf.org/html/rfc7518#section-5.2).  Additional Authenticated Data (AAD) can be used to "tag" the data for integrity checking with `"HEXAPIKEY"`.

**Comment by potatosalad** [comment]
The encoding format may also be one of the reasons why the code looks so complex, but we could potentially simplify things by using `:erlang.term_to_binary/1` and `:erlang.binary_to_term/1,2` instead of BASE64URL encoding all over the place.

Here is a working example of encryption and decryption:

##### Encryption

```elixir
alias Hex.Crypto.AES_CBC_HMAC_SHA2
alias Hex.Crypto.PBES2_HMAC_SHA2_AES_KW

# Parameters passed to encrypt/3
plain_text = "test"
password   = "password"
tag        = "apikey"

# Numeric Variables
key_length         = 64
iv_length          = 16
derived_key_length = 32
salt_length        = 16
iterations         = Hex.State.fetch!(:pbkdf2_iters) # => 32768

# Randomly Generated Variables
key  = :crypto.strong_rand_bytes(key_length)
iv   = :crypto.strong_rand_bytes(iv_length)
salt = :crypto.strong_rand_bytes(salt_length)

# Build the Protected Header
protected = (%{
  alg: "PBES2-HS512+A256KW",
  enc: "A256CBC-HS512",
  p2c: iterations,
  p2s: salt
}
|> :erlang.term_to_binary())

# Additional Authenticated Data is tag prepended onto protected
aad = tag <> protected

# Content Encryption
{cipher_text, cipher_tag} = AES_CBC_HMAC_SHA2.content_encrypt({aad, plain_text}, key, iv)

# Key Encryption
encrypted_key = PBES2_HMAC_SHA2_AES_KW.key_encrypt(key, password, salt, iterations, derived_key_length)

# Encode Encrypted Token
encrypted_token = (%{
  protected:     protected,
  encrypted_key: encrypted_key,
  iv:            iv,
  cipher_text:   cipher_text,
  cipher_tag:    cipher_tag
}
|> :erlang.term_to_binary()
|> Base.url_encode64(padding: false))
# => "g3QAAAAFZAAKY2lwaGVyX3RhZ20AAAAgc8cl9z1TbmK10DC15M0-HGn-UYSlySyPh10_TfdUuXJkAAtjaXBoZXJfdGV4dG0AAAAQRwf6W0nhc0Aq4aY-B-YvtmQADWVuY3J5cHRlZF9rZXltAAAASGdWJau_9oYD9pcMoaFZcQvYmlyiOOAAMMRB1_5Q-_8PN-5jhx0eh4iNQATYFL8b70PWx21I3xep_wdMXCH912GXZbpxOI3bXWQAAml2bQAAABAzBP8PyH3T_tWVmCdqNggzZAAJcHJvdGVjdGVkbQAAAGGDdAAAAARkAANhbGdtAAAAElBCRVMyLUhTNTEyK0EyNTZLV2QAA2VuY20AAAANQTI1NkNCQy1IUzUxMmQAA3AyY2IAAIAAZAADcDJzbQAAABDD9mRMyJkbEFUd84kOtdfj"
```

##### Decryption

```elixir
alias Hex.Crypto.AES_CBC_HMAC_SHA2
alias Hex.Crypto.PBES2_HMAC_SHA2_AES_KW

# Parameters passed to decrypt/3
cipher_text = "g3QAAAAFZAAKY2lwaGVyX3RhZ20AAAAgc8cl9z1TbmK10DC15M0-HGn-UYSlySyPh10_TfdUuXJkAAtjaXBoZXJfdGV4dG0AAAAQRwf6W0nhc0Aq4aY-B-YvtmQADWVuY3J5cHRlZF9rZXltAAAASGdWJau_9oYD9pcMoaFZcQvYmlyiOOAAMMRB1_5Q-_8PN-5jhx0eh4iNQATYFL8b70PWx21I3xep_wdMXCH912GXZbpxOI3bXWQAAml2bQAAABAzBP8PyH3T_tWVmCdqNggzZAAJcHJvdGVjdGVkbQAAAGGDdAAAAARkAANhbGdtAAAAElBCRVMyLUhTNTEyK0EyNTZLV2QAA2VuY20AAAANQTI1NkNCQy1IUzUxMmQAA3AyY2IAAIAAZAADcDJzbQAAABDD9mRMyJkbEFUd84kOtdfj"
password    = "password"
tag         = "apikey"

# This assumes everything is well-formed and does not do proper error checking.
%{
  protected:     protected,
  encrypted_key: encrypted_key,
  iv:            iv,
  cipher_text:   cipher_text,
  cipher_tag:    cipher_tag
} = (cipher_text
|> Base.url_decode64!(padding: false)
|> :erlang.binary_to_term())

# Decode the Key Manager and Content Encryptor
%{
  alg: "PBES2-HS512+A256KW",
  enc: "A256CBC-HS512",
  p2c: iterations,
  p2s: salt
} = (protected
|> :erlang.binary_to_term())

derived_key_length = 32 # based on PBES2-HS512+A256KW matched above

# Additional Authenticated Data is tag prepended onto protected
aad = tag <> protected

# Key Decryption
{:ok, key} = PBES2_HMAC_SHA2_AES_KW.key_decrypt(encrypted_key, password, salt, iterations, derived_key_length)

# Content Decryption
{:ok, plain_text} = AES_CBC_HMAC_SHA2.content_decrypt({aad, cipher_text, cipher_tag}, key, iv)
# => {:ok, "test"}
```

**Comment by ericmj** [comment]
Using `:erlang.term_to_binary/1` does seem much better, especially the decryption.

What's the benefit of generating a random key, encrypting it and then using the key to encrypt the content over the current approach?

**Comment by potatosalad** [comment]
> What's the benefit of generating a random key, encrypting it and then using the key to encrypt the content over the current approach?

The steps are actually:

1. Generate random content-encryption key (CEK)
2. Encrypt the content using the CEK
3. Encrypt the CEK using the key-encryption key (KEK)

The encrypted CEK is then stored along with the other parameters (salt, IV, authentication tag, etc).

So, I first need to acknowledge a misconception that I had in regards to whether PBKDF2 was ever supposed to be used for directly generating a content-encryption key (CEK).

In [NIST.800-132: Recommendation for Password-Based Key Derivation](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-132.pdf) (PDF link warning), _Option 1a_ is the method that is originally being used by Hex.  The changes in this pull request provide an implementation of _Option 2a_.

image

So, in defense of the original implementation using PBKDF2 to generate the CEK (not the IV), as a form of Direct Encryption, is an acceptable usage of PBKDF2.

From a usability and future features standpoint, some of the benefits of using a random CEK and wrapping with a derived KEK are:

1. Verifying the password does not attempt decryption of the content, even partially.
2. Changing the password does not require decryption and re-encryption of the content.
3. Other key management algorithms may be easily used instead of Password-Based Key Derivation.  For example, encryption based on a SSH key (RSA, EC, X25519, X448, etc), possibly by interfacing with `ssh-agent`.

From a cryptographic standpoint, [CBOR Object Signing and Encryption (COSE)](https://tools.ietf.org/html/draft-ietf-cose-msg-14#section-12.2) offers the following statements:

> Key wrapping mode is considered to be superior to direct encryption if the system has any capability for doing random key generation.  This is because the shared key is used to wrap random data rather than data that has some degree of organization and may in fact be repeating the same content.

**Comment by potatosalad** [comment]
I forgot to mention: if you'd prefer the Direct Encryption route, I can modify the code so it does that instead.

The changes involved would be:

1. Remove `Hex.Crypto.AES_KW`
2. Rename `Hex.Crypto.PBES2_HMAC_SHA2_AES_KW` to `Hex.Crypto.PBES2_HMAC_SHA2` and remove call to `Hex.Crypto.AES_KW`

**Comment by ericmj** [comment]
> I forgot to mention: if you'd prefer the Direct Encryption route, I can modify the code so it does that instead.

Let's do that and use `:erlang.term_to_binary`. Should reduce a lot of complexity. Thank you!

**Comment by ericmj** [comment]
Let me know if there's anything I can help with. Want to get the new release out soon.

**Comment by potatosalad** [comment]
Whoops, I forgot to post back here after the weekend.  I'll have something ready here today.

**Comment by potatosalad** [comment]
@ericmj Everything should be ready for code review.

Below is an updated summary of all changes made:

1. `Hex.Crypto.encrypt/3` and `Hex.Crypto.decrypt/3` are now opaque functions that take a plain/cipher text, password, and tag.  A single binary is returned containing all additional necessary data to authenticate, derive password challenges, and decrypt.
2. Instead of storing both `:key_cipher` and `:key_salt`, a single `:encrypted_key` binary is stored for the encrypted api key.
3. Added `Hex.Crypto.KeyManager` and `Hex.Crypto.ContentEncryptor` to allow for separation between Key Management and Content Encryption algorithms.
4. Altered some of the algorithms to follow guidelines in published standards:
   1. `AES-CBC` replaced with `AES_CBC_HMAC_SHA2` for authenticated content encryption [RFC 7518 Section 5.2.6](https://tools.ietf.org/html/rfc7518#section-5.2.6).
   2. `PBKDF2` replaced with `PBES2_HMAC_SHA2` for key management direct encryption [modified version of RFC 7518 Section 4.8](https://tools.ietf.org/html/rfc7518#section-4.8).
5. Added `Hex.Crypto.Encryption` to handle interactions between Key Management and Content Encryption.

As mentioned above in (1), the encryption and decryption operations are essentially opaque to the user:

```elixir
tag         = "tag"
plain_text  = "test"
password    = "password"

# Encryption
cipher_text = Hex.Crypto.encrypt(plain_text, password, tag)
# => "g3QAAAAFZAAKY2lwaGVyX3RhZ20AAAAgAGSjRxUpsqyNu-PVH5NHOhZNudVIWHJkE4r6c48jhZ1kAAtjaXBoZXJfdGV4dG0AAAAQ4Peyb_o9qkLUkDPfcul00mQADWVuY3J5cHRlZF9rZXltAAAAAGQAAml2bQAAABCLpIe9eR3onws9t41bKM_IZAAJcHJvdGVjdGVkbQAAAFqDdAAAAARkAANhbGdtAAAAC1BCRVMyLUhTNTEyZAADZW5jbQAAAA1BMjU2Q0JDLUhTNTEyZAADcDJjYgAAgABkAANwMnNtAAAAEB0Pg81wNWYU9mlpPIdjhDM"

# Decryption
Hex.Crypto.decrypt(cipher_text, password, tag)
# => {:ok, "test"}
```

Internally, the `Hex.Crypto.Encryption` module is new and is intended to help simplify the encryption operations and future maintenance.

##### AES-CBC based example

```elixir
# Content Encryption: AES256-CBC with HMAC-SHA-512
# Key Management:     Direct Encryption using PBES2 with HMAC-SHA-512
tag         = "tag"
plain_text  = "test"
password    = "password"

# Encryption
cipher_text =
  Hex.Crypto.Encryption.encrypt({tag, plain_text}, %{
    alg: "PBES2-HS512",
    enc: "A256CBC-HS512",
    p2c: 32768,
    p2s: :crypto.strong_rand_bytes(16)
  }, [
    password: password
  ])
# => "g3QAAAAFZAAKY2lwaGVyX3RhZ20AAAAgCkgFqRIn6UN2qncdF_5gYcTRVqVRtbpP9dM24apMawxkAAtjaXBoZXJfdGV4dG0AAAAQCiXChH5rCS9Tuw9pj8akXGQADWVuY3J5cHRlZF9rZXltAAAAAGQAAml2bQAAABAl5dQLRTdctdmUOUILqRBjZAAJcHJvdGVjdGVkbQAAAFqDdAAAAARkAANhbGdtAAAAC1BCRVMyLUhTNTEyZAADZW5jbQAAAA1BMjU2Q0JDLUhTNTEyZAADcDJjYgAAgABkAANwMnNtAAAAEJHqYB77gk1rLL3H7jFI2A4"

# Decryption
Hex.Crypto.Encryption.decrypt({tag, cipher_text}, [
  password: password
])
# => {:ok, "test"}
```

##### AES-GCM based example

```elixir
# Content Encryption: AES256-GCM
# Key Management:     Direct Encryption using PBES2 with HMAC-SHA-512
tag         = "tag"
plain_text  = "test"
password    = "password"

# Encryption
cipher_text =
  Hex.Crypto.Encryption.encrypt({tag, plain_text}, %{
    alg: "PBES2-HS512",
    enc: "A256GCM",
    p2c: 32768,
    p2s: :crypto.strong_rand_bytes(16)
  }, [
    password: password
  ])
# => "g3QAAAAFZAAKY2lwaGVyX3RhZ20AAAAQtrlJaTyGPRVvqV_nu9NOBGQAC2NpcGhlcl90ZXh0bQAAAARydW1zZAANZW5jcnlwdGVkX2tleW0AAAAAZAACaXZtAAAADKYbCwfI2gewsFnH-GQACXByb3RlY3RlZG0AAABUg3QAAAAEZAADYWxnbQAAAAtQQkVTMi1IUzUxMmQAA2VuY20AAAAHQTI1NkdDTWQAA3AyY2IAAIAAZAADcDJzbQAAABCRKETKViKKNHkTkrHdKY7_"

# Decryption
Hex.Crypto.Encryption.decrypt({tag, cipher_text}, [
  password: password
])
# => {:ok, "test"}
```

**Comment by ericmj** [comment]
Thank you! :heart:

**Pull request merged**
