### PR TITLE
Build of rebar3 and upload for specific Elixir versions

### PR DESCRIPTION
**Pull request by ericmj**
This changes the construction of the CSV file so we keep the rebar build
for old Elixir versions (1.0.0) while being able to add it for new
Elixir versions (1.11.4).

### CODE REVIEW

**Comment by josevalim** [comment]
@ericmj it looks good to me! Do you have an example of how the CSV looks like? In any case, after this is merged and a new version is published, I will try it out on Elixir master. :)

**Comment by ericmj** [comment]
> Do you have an example of how the CSV looks like? 

```
3.13.1,1323dec786a1642c50c29cf6601bc4e1888de9918527676b657394f75dfb873ce8b27d818ceaed4f76bcbc615cd14680e2ce2027e7d7d37e4db575be29574cd0,1.0.0
3.14.4,91398aafe4d09f02b824202e1667210a59a2bba6704caf0a643f26bc5a87070c710cfd167ede7a8f0d772b68ba0ac95f47ddc785dfcf6cbc0ac09bfe1bab347b,1.11.4
```

> In any case, after this is merged and a new version is published, I will try it out on Elixir master.

I have uploaded `rebar3-3.14.4` so if you swap out the CSV to the one above and skip the signature check you should be able to try it now.

**Comment by josevalim** [comment]
I have given it a try and it looks good to me. We can ship the new CSV. As soon as the new CSV is pushed, please run a `mix local.rebar` on a stable Elixir version and see if it all works fine. :) Then I will continue with my testing for master. Thank you! :heart:

**Review by wojtekmach — APPROVED** [review]

**Comment by ericmj** [comment]
Rebar 3.14.4 has been published to repo.hex.pm now.

**Pull request merged**
