### PR TITLE
Explains behaviour with overridden deps

### PR DESCRIPTION
**Pull request by DianaOlympos**
The case of an overridden deps not being updated happened to me a few weeks ago. @ericmj offered to update the docs. This is my take on trying to express the problem.

### CODE REVIEW

**Comment by ericmj** [comment]
Sorry I don't remember this discussion. Can you show an example of scenario where an overridden dependency causes `mix hex.outdated / mix deps.update` to be confusing?

**Comment by DianaOlympos** [comment]
And you are right to ask because i totally misremembered the problem. I knew i should have made a repo case. It is not the override, it is an optional deps.

Here is a repro case, https://github.com/DianaOlympos/optional_repro_hex_outdated

`mix hex.outdated` tell us we can update `ex_aws` but `mix deps.update ex_aws` does nothing, because the bump from 2.1.0 to 2.1.1 ask for `{:configparser_ex,  ~> 4.0"}`

I will fix the PR.

**Comment by DianaOlympos** [comment]
Commit message is temporary. I will squash once we are happy.

I am not a fan of the current explanation that i offer. I will think to see if i find a better case.

Do you want me to rename the PR too ?

**Comment by ericmj** [comment]
Thanks for the clarification. But I think we can remove the "optional dependency" part since it will be true for non-optional deps as well. For example you have two deps:

```
{:a, "~> 1.0"} locked to 1.0.0
{:b, "~> 1.0"} locked to 1.0.0
```

There is a newer version `:b 1.1.0`, but it bumps to the requirement on `:a` to `~> 2.0`. `:b` will show as updatable in `mix hex.outdated` but won't update due to the new requirement that doesn't match the `~> 1.0` in your `mix.exs` file.

**Comment by DianaOlympos** [comment]
Updated. Sorry for the delay, real life happened. 

I find the wording atrocious, but i hope that with calling it out, more people will think of the wording.

**Comment by DianaOlympos** [comment]
@ericmj What do you think ?

**Comment by ericmj** [comment]
Thanks for the PR @DianaOlympos.

I decided to do a more general explanation of the problem instead: https://github.com/hexpm/hex/commit/cadfc33f6b4e7713d63c39fceb05818295952793.

**Comment by DianaOlympos** [comment]
Thanks this works far better than my try.

❤️ 💜 💚 💙 💛

**Pull request closed without merging**
